name: futquiz
description: A new Flutter project.
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  http: ^1.1.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.3.0
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  easy_autocomplete: ^1.6.0
  animations: ^2.0.8
  confetti: ^0.7.0
  lottie: ^2.6.0
  package_info_plus: ^4.1.0
  firebase_ui_oauth_google: ^1.2.11
  firebase_ui_auth: ^1.8.0
  firebase_auth: ^4.9.0
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
