// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvn8aSw3f5gZPDgCGsKLWavWIrYNMvFMs',
    appId: '1:964796347193:web:300f103dbed8373b102ee8',
    messagingSenderId: '964796347193',
    projectId: 'futquiz-261d5',
    authDomain: 'futquiz-261d5.firebaseapp.com',
    storageBucket: 'futquiz-261d5.appspot.com',
    measurementId: 'G-2K27LZ38YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbArL6n55ovJNi73BlPIAc0aBd91hkLU0',
    appId: '1:964796347193:android:105d1947dce44ae0102ee8',
    messagingSenderId: '964796347193',
    projectId: 'futquiz-261d5',
    storageBucket: 'futquiz-261d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-hh1_affT0L5Q6vUWy6vyiWW6cGsflI',
    appId: '1:964796347193:ios:d5ecf88d45b88c91102ee8',
    messagingSenderId: '964796347193',
    projectId: 'futquiz-261d5',
    storageBucket: 'futquiz-261d5.appspot.com',
    iosClientId: '964796347193-a3am9l0vd1mqkpcqhutgddqko0q1tj7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.futquiz',
  );
}
